Import("env")
b = ModelBuilder(env)

model = "extruder-fan-5015.scad"
backpack_model = "5015-mp1584-backpack.scad"

for opts in GenerateOptions(
    eyelet=[("bolt", "m4-bolts"), ("insert", "hot-melt-inserts")]
):
    b.STL(
        f"sovol-sv06-extruder-fan-duct-5015-{opts.eyelet_fn}.stl",
        model,
        {"Render_Mode": "print", "Eyelet_Type": opts.eyelet},
        zip_dir="models-for-printing",
    )

for opts in GenerateOptions(mode=["normal", ("preview", "-preview")]):
    b.Image(
        f"demo{opts.mode_fn}.png",
        model,
        {"Render_Mode": opts.mode},
        camera="20,-15,0,70,0,10,200",
    )

b.STL(f"5015-mp1584-backpack.stl", backpack_model, {"Render_Mode": "print"})

b.Image(
    "demo-5015-mp1584-backpack.png", backpack_model, {"Render_Mode": "preview"}
)

b.Source(
    "*.scad",
    "leander-perez-blanco-*.stl",
    "FarmerKGBOfficer-*.stl",
    "sovol-*.STL",
)

b.add_default_targets()

# vim: ft=python
