Import("env")
b = ModelBuilder(env)

model = "rugged-box-gridfinity.scad"
model_dependencies = ["rugged-box-library.scad"]

gridfinity_boxes = {
    (
        f"{opts.gridfinity_stackable_fn}"
        f"-{opts.d[0]}x{opts.d[1]}x{opts.d[2]+opts.d[3]}"
    ): (
        list(opts.d)
        + [
            opts.d[0] >= 4 and opts.d[3] >= 6,
            {"Gridfinity_Stackable": opts.gridfinity_stackable},
        ]
    )
    for opts in GenerateOptions(
        gridfinity_stackable=[(0, "plain"), (1, "gridfinity-stackable")],
        d=[
            (dims,)
            for dims in [
                [4, 2, 2, 4],
                [4, 4, 2, 4],
                [4, 2, 2, 7],
                [4, 4, 2, 7],
                [6, 4, 2, 7],
                [6, 6, 2, 7],
                [6, 4, 2, 10],
                [6, 6, 2, 10],
            ]
        ],
    )
}

for box_name, (
    width,
    length,
    top_height,
    bottom_height,
    enable_handle,
    *params,
) in gridfinity_boxes.items():
    for opts in GenerateOptions(part=["top", "bottom", "handle"]):
        if not enable_handle and opts.part == "handle":
            continue
        part_params = {
            **{
                "Part": opts.part,
                "Width": width,
                "Length": length,
                "Top_Height": top_height,
                "Bottom_Height": bottom_height,
                "Top_Grip": 1,
            },
            **(params[0] if params else {}),
        }
        b.STL(
            f"gridfinity-box-{box_name}-{opts.part}.stl",
            model,
            part_params,
            model_dependencies,
            zip_dir=box_name,
        )

for opts in GenerateOptions(latch_type=["clip", "draw"]):
    b.STL(
        f"{opts.latch_type}-latch.stl",
        model,
        {"Part": "latch", "Latch_Type": opts.latch_type},
        model_dependencies,
        zip_dir="latches",
    )
b.STL(
    f"stacking-latch.stl",
    model,
    {"Part": "stacking_latch"},
    model_dependencies,
    zip_dir="latches",
)

b.add_default_targets()

b.Image(
    "demo-dimensions.gif",
    model,
    [
        {
            **{
                "Part": part,
                "Width": width,
                "Length": length,
                "Top_Height": top_height,
                "Bottom_Height": bottom_height,
            },
            **(params[0] if params else {}),
        }
        for part, width, length, top_height, bottom_height, *params in [
            ("assembled_open", 4, 2, 2, 4, {"Latch_Type": "clip"}),
            ("assembled_open", 4, 2, 2, 5, {"Latch_Type": "clip"}),
            ("assembled_open", 4, 2, 2, 6, {"Latch_Type": "draw"}),
            ("assembled_open", 4, 2, 2, 7, {"Latch_Type": "draw"}),
            ("assembled_open", 5, 2, 2, 7, {"Latch_Type": "draw"}),
            ("assembled_open", 6, 2, 2, 7, {"Latch_Type": "draw"}),
            ("assembled_open", 6, 3, 2, 7, {"Latch_Type": "draw"}),
            ("assembled_open", 6, 4, 2, 7, {"Latch_Type": "draw"}),
            ("assembled_closed", 6, 4, 2, 7, {"Latch_Type": "draw"}),
            ("assembled_closed", 6, 4, 2, 6, {"Latch_Type": "draw"}),
            ("assembled_closed", 6, 4, 2, 5, {"Latch_Type": "clip"}),
            ("assembled_closed", 6, 4, 2, 4, {"Latch_Type": "clip"}),
            ("assembled_closed", 5, 4, 2, 4, {"Latch_Type": "clip"}),
            ("assembled_closed", 4, 4, 2, 4, {"Latch_Type": "clip"}),
            ("assembled_closed", 4, 3, 2, 4, {"Latch_Type": "clip"}),
            ("assembled_closed", 4, 2, 2, 4, {"Latch_Type": "clip"}),
        ]
    ],
)

for camera_opts in GenerateOptions(
    camera=[("0,0,0,55,0,25,800", "top"), ("0,0,40,135,0,25,800", "bottom")],
):
    b.Image(
        f"demo-stacking-{camera_opts.camera_fn}.png",
        model,
        [
            {
                "Part": "assembled_closed",
                "Width": 6,
                "Length": 4,
                "Top_Height": 2,
                "Bottom_Height": 7,
                "Gridfinity_Stackable": opts.stackable,
            }
            for opts in GenerateOptions(stackable=[0, 1])
        ],
        tile="2x1",
        camera=camera_opts.camera,
    )

# vim: ft=python
