Import("env")
b = ModelBuilder(env)

model = "garage-reed-switch-bracket.scad"

for opts in GenerateOptions(part=["front", "back"]):
    b.STL(
        f"garage-reed-switch-bracket-{opts.part}.stl",
        model,
        {"Part": opts.part},
    )
b.Image("demo.png", model, {"Part": "both"})

b.add_default_targets()

# vim: ft=python
