Import("env")
b = ModelBuilder(env)

model = "extruder-runout-mount.scad"

for orientation in {"rear", "right"}:
    b.STL(
        f"extruder-runout-mount-connector-facing-{orientation}.stl",
        model,
        {
            "Render_Mode": "print",
            "Round_Edges": 1,
            "Runout_Sensor_Orientation": orientation,
        },
    )

for render_mode, file_name, camera in [
    ("normal", "part", None),
    ("model_preview", "model-preview", "20,20,25,55,0,25,350"),
]:
    b.Image(
        f"render-{file_name}.png",
        model,
        {
            "$fn": 25,
            "Render_Mode": render_mode,
            "Round_Edges": 1,
            "Runout_Sensor_Orientation": "right",
        },
        camera=camera,
    )

b.Image(
    f"demo-rotation.gif",
    model,
    [
        {
            "$fn": 25,
            "Render_Mode": "model_preview",
            "Round_Edges": 1,
            "Runout_Sensor_Orientation": orientation,
        }
        for orientation in {"rear", "right"}
    ],
    camera="20,20,25,55,0,25,350",
    delay=150,
)


b.add_default_targets()

# vim: ft=python
