from types import SimpleNamespace

Import("env")
b = ModelBuilder(env)

basic_model = "ferris-wheel-base.scad"
fancy_model = "ferris-wheel-base-fancy.scad"

for opts in GenerateOptions(
    model=[
        (SimpleNamespace(model=basic_model, args={}), ""),
        (
            SimpleNamespace(
                model=fancy_model, args={"Honeycomb": 1, "Round_All_Edges": 1}
            ),
            "-fancy",
        ),
    ]
):
    b.STL(
        f"ferris-wheel-base{opts.model_fn}.stl",
        opts.model.model,
        opts.model.args,
    )
    b.Image(f"demo{opts.model_fn}.png", opts.model.model, opts.model.args)

b.add_default_targets()

# vim: ft=python
