Import("env")
b = ModelBuilder(env)

model = "mp1584-case.scad"

for opts in GenerateOptions(
    part=["top", "bottom"], interlock=["default", "opposite"]
):
    b.STL(
        f"mp1584-case-{opts.part}-{opts.interlock}.stl",
        model,
        {"Part": opts.part, "Interlock_Style": opts.interlock},
    )

b.Image("demo.png", model, {"Part": "both_assembled"})

b.Image(
    "demo-row.png",
    model,
    [
        {"Part": "top"},
        {"Part": "bottom"},
        {"Part": "both_assembled"},
    ],
    tile="3x1",
)

b.InsetImage(
    "photo-demo-inset.jpg",
    "photo-offset.jpg",
    "demo-row.png",
    resize="25%",
    gravity="south",
)

b.add_default_targets()

# vim: ft=python
