Import("env")
b = ModelBuilder(env)

model = "mp1584-case.scad"

for opts in GenerateOptions(
    part=["top", "bottom"], interlock=["default", "opposite"]
):
    b.STL(
        f"mp1584-case-{opts.part}-{opts.interlock}.stl",
        model,
        {"Part": opts.part, "Interlock_Style": opts.interlock},
    )
b.Image("demo.png", model, {"Part": "both_assembled"})

b.add_default_targets()

# vim: ft=python
