Import("env")
b = ModelBuilder(env)

model = "toy-shopping-basket-handle.scad"

b.STL("toy-shopping-basket-handle.stl", model)
b.Image(model, "render.png", camera="90,20,0,55,0,25,350")

b.add_default_targets()

# vim: ft=python
