Import("env")
b = ModelBuilder(env)

model = "stargate.scad"

for diameter in [100, 150, 200]:
    for symbols_style in ["inset", "raised"]:
        fn_symbols_style = f"-{symbols_style}-symbols"
        for hanging_loop in [0, 1]:
            fn_hanging_loop = "-ornament" if hanging_loop else ""
            zip_hanging_loop = "ornament-" if hanging_loop else ""
            for double_sided in [0, 1]:
                fn_double_sided = "-double-sided" if double_sided else ""
                b.STL(
                    (
                        f"stargate-{diameter}mm{fn_symbols_style}"
                        f"{fn_double_sided}{fn_hanging_loop}.stl"
                    ),
                    model,
                    {
                        "Symbols_Style": symbols_style,
                        "Diameter": diameter,
                        "Double_Sided": double_sided,
                        "Hanging_Loop": hanging_loop,
                    },
                    zip_dir=f"{zip_hanging_loop}{diameter}mm",
                )
        for supports in [0, 1]:
            supports_fn = "-supports" if supports else ""
            b.STL(
                (
                    f"stargate-handle-{diameter}mm"
                    f"{fn_symbols_style}{supports_fn}.stl"
                ),
                "stargate-handle.scad",
                {
                    "Symbols_Style": symbols_style,
                    "Hole_Spacing": diameter,
                    "Print_Supports": supports,
                },
                zip_dir=f"handle-{diameter}mm",
            )
    b.STL(
        f"stargate-handle-{diameter}mm-drill-guide.stl",
        "stargate-handle.scad",
        {"Part_Selection": "drill-guide", "Hole_Spacing": diameter},
        zip_dir=f"{diameter}mm",
    )

b.Image(
    "render-stargate.png",
    model,
    {"Symbols_Style": "inset", "Diameter": 150},
    camera="0,-5,0,33,0,0,350",
)
b.Image(
    "render-stargate-ornament.png",
    model,
    {"Symbols_Style": "inset", "Diameter": 150, "Hanging_Loop": 1},
    camera="0,0,0,33,0,0,375",
)
b.Image(
    "render-stargate-handle.png",
    "stargate-handle.scad",
    {"Symbols_Style": "inset", "Hole_Spacing": 150, "Print_Supports": 0},
    camera="0,15,30,75,0,25,350",
)
b.Image(
    "render-stargate-handle-drill-guide.png",
    "stargate-handle.scad",
    {"Part_Selection": "drill-guide", "Hole_Spacing": 150},
)

b.InsetImage(
    "demo-inset.png",
    "render-stargate.png",
    "photo-stargate-handle.jpg",
    resize="33%",
    gravity="southeast",
)

b.Source("*.scad", "stargate-symbols.svg")

b.add_default_targets()

# vim: ft=python
