Import("env")
b = ModelBuilder(env)

model = "nipper-holder.scad"

for opts in GenerateOptions(variant=[(1, "-plain"), (2, "-screw-hole")]):
    b.STL(
        f"nipper-holder-remix{opts.variant_fn}.stl",
        model,
        {"Model_Variant": opts.variant},
        zip_dir="models-for-printing",
    )
    b.Image(
        f"render-variant{opts.variant_fn}.png",
        model,
        {"Model_Variant": opts.variant},
        camera="5,0,5,45,0,-45,140",
    )

b.Source("*.scad", "muh60-*.stl")

b.add_default_targets()

# vim: ft=python
