Import("env")
b = ModelBuilder(env)

mainboard_model = "mainboard-cable-support.scad"

b.STL(
    f"mainboard-cable-support.stl",
    mainboard_model,
    {"Print_Orientation": 1},
)
for opts in GenerateOptions(
    render_mode=[("normal", ""), ("model_preview", "-model-preview")]
):
    b.Image(
        f"render-mainboard-support{opts.render_mode_fn}.png",
        mainboard_model,
        {"Render_Mode": opts.render_mode},
    )

b.add_default_targets()

# vim: ft=python
