Import("env")
b = ModelBuilder(env)

mainboard_model = "mainboard-cable-support.scad"

b.STL(
    f"mainboard-cable-support.stl",
    mainboard_model,
    {"Print_Orientation": 1},
    zip_dir="model-for-printing",
)
for opts in GenerateOptions(
    render_mode=[("normal", ""), ("model_preview", "-model-preview")]
):
    b.Image(
        f"render-mainboard-support{opts.render_mode_fn}.png",
        mainboard_model,
        {"Render_Mode": opts.render_mode},
    )

b.InsetImage(
    "photo-inset.jpg",
    "photo-installed.jpg",
    "render-mainboard-support-model-preview.png",
    gravity="southeast",
    resize="33%",
)

b.Source("*.scad", "itsrouteburn-*.stl", "sovol-*.stl")

b.add_default_targets()

# vim: ft=python
