Import("env")
b = ModelBuilder(env)

model = "project-box.scad"

dimensions = [
    [
        (45, 32, 25),
    ],
]

for opts in GenerateOptions(part=["lid", "box"], dims=dimensions):
    dims = opts.dims[0]
    b.STL(
        f"{opts.part}-{dims[0]}x{dims[1]}x{dims[2]}.stl",
        model,
        {"Part": opts.part, "Dimensions": dims, "PCB_Mount": 0},
    )
b.Image("demo.png", model, {"Part": "all", "preview_render": 1})

b.add_default_targets()

# vim: ft=python
