Import("env")
b = ModelBuilder(env)

model = "keyboard-tray-slide-cap.scad"

b.STL(model, "keyboard-tray-slide-cap.stl")
b.Image(model, "demo.png", {"$fn": 50})

b.add_default_targets()

# vim: ft=python
