Import("env")
b = ModelBuilder(env)

model = "mainboard-fan-mp1584.scad"

b.STL(
    "mainboard-fan-mp1584.stl",
    model,
    {"Render_Mode": "print"},
    zip_dir="models-for-printing",
)
b.Image("demo.png", model, {"Render_Mode": "preview"})

b.Source("*.scad", "sovol-*.stl")

b.add_default_targets()

# vim: ft=python
