Import("env")
b = ModelBuilder(env)

drain_nut_model = "drain-nut.scad"
gasket_model = "gasket.scad"

for opts in GenerateOptions(nut=["G5/8", "G1-1/4", "G1-1/2"]):
    b.STL(
        f"drain-nut-{opts.nut.replace('/', '_')}.stl",
        drain_nut_model,
        {
            "Nut_Type": opts.nut,
            "Grip_Thickness": 4,
            "Grip_Length": 10,
            "Thickness": 3,
            "Thread_Slop": 0.2,
            "Height": 15,
        },
    )

b.STL(
    "stopper-nut-G5_8.stl",
    drain_nut_model,
    {
        "Nut_Type": "Custom",
        "Thread_Diameter": 23.6,
        "Thread_Pitch": 1.3,
        "Thread_Depth": 0.7,
        "Custom_Narrow_Diameter": 14.2,
        "Custom_Ball_Diameter": 20.4,
        "Height": 12,
        "Thickness": 3,
        "Thread_Slop": 0.2,
        "Shape": "hexagonal",
        "Wing_Grips": 1,
        "Mini_Grips": 0,
        "Grip_Length": 8,
        "Ball_Cut": 1,
        "Chamfer_Inner_Ring": 0,
        "Thread_Setback_Height": 2,
        "Thread_End_Offset": 0,
    },
)

b.STL(
    "wall-drain-nut-G1-1_4.stl",
    drain_nut_model,
    {
        "Nut_Type": "G1-1/4",
        "Grip_Thickness": 4,
        "Grip_Length": 10,
        "Thickness": 5,
        "Thread_Slop": 0.5,
        "Thread_Setback_Height": 1,
        "Height": 18,
        "Lip_Height": 5,
    },
)

b.STL(
    "wall-drain-nut-O-ring-G1-1_4.stl",
    gasket_model,
    {"Gasket_Type": "G1-1/4"},
)

b.STL(
    "stopper-nut-O-ring.stl",
    gasket_model,
    {
        "Gasket_Type": "Custom",
        "Style": "ball-inset",
        "Height": 2.5,
        "Outer_Diameter": 19,
        "Inner_Diameter": 14,
    },
)

b.STL(
    "stopper-nut-O-ring-smaller.stl",
    gasket_model,
    {
        "Gasket_Type": "Custom",
        "Style": "ball-inset",
        "Height": 2.5,
        "Outer_Diameter": 18,
        "Inner_Diameter": 13,
    },
)

b.STL(
    "stopper-nut-O-ring-square.stl",
    gasket_model,
    {
        "Gasket_Type": "Custom",
        "Style": "square",
        "Height": 2.5,
        "Outer_Diameter": 19,
        "Inner_Diameter": 14,
    },
)


b.Image("demo.png", drain_nut_model)

b.add_default_targets()

# vim: ft=python
