Import("env")
b = ModelBuilder(env)

model = "logitech-c920-slim-adapter.scad"

link_types = ["male", "female", "male_flat", "none"]

for link_type in link_types:
    b.STL(
        f"logitech-c920-slim-adapter-{link_type}.stl",
        model,
        {"Link_Type": link_type},
        zip_dir="models-for-printing",
    )

b.Image(
    "demo.png",
    model,
    [{"Link_Type": link_type} for link_type in link_types],
    camera="0,2,5,55,0,70,120",
)

b.Source("*.scad", "sneaks-*.stl")

b.add_default_targets()

# vim: ft=python
