Import("env")
b = ModelBuilder(env)

model = "logitech-c920-slim-adapter.scad"

link_types = ["male", "female", "male_flat", "none"]

for link_type in link_types:
    for ball_mount in [0, 1]:
        fn_ball_mount = "-ball" if ball_mount else ""
        b.STL(
            f"logitech-c920-slim-adapter-{link_type}{fn_ball_mount}.stl",
            model,
            {"Link_Type": link_type, "Ball_Mount": ball_mount},
            zip_dir="models-for-printing",
        )

b.Image(
    "demo.png",
    model,
    [
        {"Link_Type": "female", "Ball_Mount": 0},
        {"Link_Type": "male", "Ball_Mount": 0},
        {"Link_Type": "none", "Ball_Mount": 1},
        {"Link_Type": "male", "Ball_Mount": 1},
    ],
    camera="0,2,0,55,0,70,125",
)

b.Source("*.scad", "sneaks-*.stl")

b.add_default_targets()

# vim: ft=python
