Import("env")
b = ModelBuilder(env)

model = "bicycle-taillight-clip.scad"

for opts in GenerateOptions(style=["single", "double"]):
    b.STL(
        f"bicycle-taillight-clip-{opts.style}.stl",
        model,
        {"Style": opts.style},
    )
b.Image("demo.png", model)

b.add_default_targets()

# vim: ft=python
