Import("env")
b = ModelBuilder(env)

model = "slide-lock-magnet.scad"

for opts in GenerateOptions(part=["base", "lid"]):
    b.STL(f"slide-lock-magnet-{opts.part}.stl", model, {"Part": opts.part})
b.Image("demo.png", model, {"Part": "both"})

b.add_default_targets()

# vim: ft=python
