Import("env")
b = ModelBuilder(env)

model = "spool-holder.scad"

# build/printables-sovol-sv06-plus__spool-holder-remix.zip

for file_name, part_name in {
    "barrel-full-size": "barrel",
    "nut-extended-size": "nut",
}.items():
    b.STL(
        f"spool-holder-{file_name}.stl",
        model,
        {"Part": part_name, "Nut_Extra_Length": 15},
        zip_dir="models-for-printing",
    )

b.Asset(
    "rogerquin-sv06-spool-holder-barrel-fitting.stl",
    zip_dir="models-for-printing",
)

b.Source(
    "*.scad",
    "rogerquin-SV06_Spool_Holder_extended_nut_med_res_V1.stl",
    "rogerquin-sv06-spool-holder-barrel.stl",
    "rogerquin-sv06-spool-holder-nut.stl",
    "rogerquin-sv06-spool-holder-sunlu-barrel-adapter.stl",
    "rogerquin-sv06-spool-holder-sunlu-nut.stl",
)

b.Asset(
    "sovol-sv06-JXHSV06-07002-d Filament Barrel.STL",
    "sovol-sv06-filament-barrel-1mm-chamfered-threads.stl",
    "sovol-sv06-filament-barrel-2mm-chamfered-threads.stl",
    zip_dir="stock-sv06-filament-barrel",
)

b.Image(
    "render-sunlu-combined-barrel.png",
    model,
    {"Part": "barrel"},
)
b.Image("render-sunlu-nut.png", model, {"Part": "nut"})
b.Image("render-all-parts-preview.png", model, {"Part": "preview"})

b.add_default_targets()

# vim: ft=python
