Import("env")
b = ModelBuilder(env)

model = "ip6518-case.scad"

b.STL("ip6518-case-top.stl", model, {"Render_Top": 1, "Render_Bottom": 0})
for i, mount_holes_type in enumerate(["no", "side", "sv06-psu"]):
    b.STL(
        f"ip6518-case-bottom-{mount_holes_type}-mount-holes.stl",
        model,
        {"Render_Top": 0, "Render_Bottom": 1, "Mount_Holes": i},
    )

b.add_default_targets()

# vim: ft=python
