Import("env")
b = ModelBuilder(env)

b.Image(
    "demo.png",
    "render-image.scad",
    {"Part": "male"},
    camera="10,20,0,330,20,0,250",
)

# Package model and input STLs together
b.Source(
    "x-axis-left-mount-block-articulated-camera-female.stl",
    "x-axis-left-mount-block-articulated-camera-male.stl",
    "x-axis-left-mount-block-blank.stl",
)

b.add_default_targets()

# vim: ft=python
