Import("env")
b = ModelBuilder(env)

model = "kirby-fume-extractor.scad"

for opts in GenerateOptions(
    part=[
        "back",
        "face",
        "grill",
        "inner-spacer",
        "feet-connector",
        "left-foot",
        "right-foot",
        "pin",
        "left-arm",
        "right-arm",
        "eye",
        "eye-insert-white",
        "eye-insert-blue",
        "wire-shield",
    ]
):
    for attach_opts in GenerateOptions(
        attach=(
            [("screws", "-screws"), ("inserts", "-heat-set-inserts")]
            if opts.part in {"back", "wire-shield"}
            else ["screws"]
        )
    ):
        b.STL(
            f"kirby-fume-extractor-{opts.part}{attach_opts.attach_fn}.stl",
            model,
            {
                "Part": opts.part,
                "Fan_Attachment": attach_opts.attach,
                "Hole_Diameter": (
                    4.0 if attach_opts.attach == "screws" else 5.5
                ),
            },
        )

b.Image("demo.png", model, {"Part": "preview"})

b.Source("*.scad", "chrisborge-*.stl", "josteing-*.stl")

b.add_default_targets()

# vim: ft=python
