Import("env")
b = ModelBuilder(env)

model = "bed-strain-relief-support-v2.scad"

b.STL(
    "bed-strain-relief-support-v2.stl",
    model,
    {"Print_Orientation": 1},
    zip_dir="models-for-printing",
)

b.Image("bed-strain-relief-render.png", model, {"Print_Orientation": 0})
b.Image("frame-strain-relief-render.png", "frame-strain-relief-support.scad")

b.Image(
    "renders-row.png",
    ["frame-strain-relief-support.scad", model],
    [None, {"Print_Orientation": 0}],
)

b.InsetImage(
    "photo-inset.jpg",
    "v2-photo1.jpg",
    "renders-row.png",
    resize="25%",
    gravity="southeast",
)

b.Asset(
    "*.scad",
    "sovol-sv06plus-cover-repaired-notext.stl",
    "sovol-sv06plus-cover-repaired.stl",
    "sovol-sv06plus-JXHSV06-01009-d Hot Bed Wire Fixing Cover.STL",
    zip_dir="bed-support-source-model",
)

b.Asset("frame-strain-relief-support.stl", zip_dir="models-for-printing")

b.Asset(
    "bed-strain-relief-support-v1/bed-strain-relief-support-v1.stl",
    zip_dir="old-version",
)

b.add_default_targets()

# vim: ft=python
