Import("env")
b = ModelBuilder(env)

bed_model = "bed-strain-relief-support-v2.scad"
frame_model = "frame-strain-relief-support-v2.scad"

b.STL(
    "bed-strain-relief-support-v2.stl",
    bed_model,
    {"Print_Orientation": 1},
    zip_dir="models-for-printing",
)
for opts in GenerateOptions(
    angle=[(60, "-60-degrees"), (75, "-75-degrees"), (90, "-90-degrees")]
):
    b.STL(
        f"frame-strain-relief-support-v2{opts.angle_fn}.stl",
        frame_model,
        {"Print_Orientation": 1, "Angle": opts.angle},
        zip_dir="models-for-printing",
    )

b.Image("bed-strain-relief-render.png", bed_model, {"Print_Orientation": 0})
b.Image(
    "frame-strain-relief-render.png", frame_model, {"Print_Orientation": 0}
)

b.Image(
    "frame-strain-relief-options.gif",
    frame_model,
    [
        {"Angle": angle, "Radius": radius}
        for (angle, radius) in [
            (60, 27.5),
            (75, 27.5),
            (90, 27.5),
            (90, 35),
            (90, 40),
            (75, 40),
            (60, 40),
            (60, 35),
            (60, 27.5),
        ]
    ],
    camera="0,0,40,165,290,0,250",
)

b.Image(
    "renders-row.png",
    [frame_model, bed_model],
    [{"Print_Orientation": 0}] * 2,
)

b.InsetImage(
    "photo-inset.jpg",
    "v2-photo1.jpg",
    "renders-row.png",
    resize="25%",
    gravity="southeast",
)

b.Source(
    "*.scad",
    "rogerquin-*.stl",
    "sovol-*.stl",
    "sovol-*.STL",
)

b.Asset(
    "strain-relief-support-v1/*.stl",
    zip_dir="old-version",
)

b.add_default_targets()

# vim: ft=python
