Import("env")
b = ModelBuilder(env)

model = "bathtub-drain-hair-catcher.scad"

for top_style in {"winged-round", "winged-angled"}:
    for supports in {0, 1}:
        fn_supports = "-with-supports" if supports == 1 else ""
        fn = f"bathtub-drain-hair-catcher-{top_style}{fn_supports}.stl"
        b.STL(
            fn,
            model,
            {
                "Print_Orientation": 0,
                "Print_Supports": supports,
                "Top_Style": top_style,
                "Bottom_Style": "flat",
            },
        )

for bottom_style in {"flat", "angled"}:
    fn = f"bathtub-drain-hair-catcher-flat-top-{bottom_style}-bottom.stl"
    b.STL(
        fn,
        model,
        {
            "Print_Orientation": 1,
            "Print_Supports": 0,
            "Top_Style": "flat",
            "Bottom_Style": bottom_style,
        },
    )

for top_style in {"winged-round", "winged-angled"}:
    for supports in {0, 1}:
        fn_supports = "-supports" if supports == 1 else ""
        fn = f"demo-{top_style}{fn_supports}.png"
        b.Image(
            model,
            fn,
            {
                "$fn": 50,
                "Print_Orientation": 0,
                "Print_Supports": supports,
                "Top_Style": top_style,
            },
        )

b.add_default_targets()

# vim: ft=python
