---
name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: 💾 Check out repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: 🌿 Fetch base branch
        run: |
          git fetch origin "${GITHUB_BASE_REF}"

      - name: 🪝 Cache prek hooks
        uses: actions/cache@v6
        with:
          path: ~/.cache/prek
          key: "prek-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}"

      - name: 🛠️ Install tools
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y openscad xvfb pandoc texlive-xetex

      - name: 🍳 Set up mise
        uses: jdx/mise-action@v4
        with:
          cache: true
          install: true

      - name: 📐 Run static checks
        run: mise run lint

      - name: 🏗️ Render models
        run: xvfb-run scons ref="origin/${GITHUB_BASE_REF}"
        # Only render models for pull requests
        if: ${{ github.event_name == 'pull_request' }}

      - name: 📦 Save artifacts
        uses: actions/upload-artifact@v7
        with:
          name: "Rendered Models"
          path: |
            **/build/*
            !**/build/**/*.deps

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
