Import("env")
b = ModelBuilder(env)

model = "swatch-bin.scad"

for grid_x in range(1, 2 + 1):
    for grid_y in range(1, 4 + 1):
        if grid_x == 2 and grid_y == 1:
            continue
        b.STL(
            model,
            f"swatch-bin-{grid_x}x{grid_y}x3.stl",
            {
                "gridx": grid_x,
                "gridy": grid_y,
                "gridz": 3,
                "Separator_Style": 1,
            },
        )

b.Image(
    model,
    "demo.gif",
    [
        {
            "gridx": grid_x,
            "gridy": grid_y,
            "gridz": grid_z,
            "Separator_Style": separator_style,
        }
        for grid_x, grid_y, grid_z, separator_style in [
            [2, 3, 3, 1],
            [2, 2, 3, 1],
            [2, 1, 3, 1],
            [1, 1, 3, 1],
            [1, 1, 3, 2],
            [1, 2, 3, 2],
            [1, 2, 3, 2],
            [1, 3, 3, 2],
            [1, 3, 3, 0],
            [1, 4, 3, 0],
            [1, 4, 4, 0],
            [1, 4, 5, 0],
            [1, 4, 6, 0],
            [2, 4, 6, 0],
            [2, 3, 6, 0],
            [2, 3, 6, 1],
            [2, 3, 5, 1],
            [2, 3, 4, 1],
        ]
    ],
    camera="-10,5,0,50,0,20,375",
)

b.add_default_targets()

# vim: ft=python
