Import("env")
b = ModelBuilder(env)

dual_spool_holder_model = "dual-spool-holder.scad"
filament_barrel_model = "filament-barrel.scad"

b.STL(
    "dual-spool-holder.stl",
    dual_spool_holder_model,
    {"Render_Mode": "print"},
    zip_dir="models-for-printing",
)

for opts in GenerateOptions(chamfer=[(0, "-stock"), (1, "-chamfered")]):
    b.STL(
        f"filament-barrel{opts.chamfer_fn}.stl",
        filament_barrel_model,
        {"Chamfer": opts.chamfer},
        zip_dir="models-for-printing",
    )

b.Image(
    "render-part.png",
    dual_spool_holder_model,
    {"Render_Mode": "normal", "Image_Render": 1},
)
b.Image(
    "render-filament-barrel.png",
    filament_barrel_model,
    {"Chamfer": 1},
    camera="0,0,50,125,0,10,300",
)

b.Image(
    "render-model-preview.png",
    dual_spool_holder_model,
    {"Render_Mode": "model_preview", "Image_Render": 1},
    camera="0,0,90,55,0,25,900",
)

b.Image(
    "demo-dual-spool-holder-tilt-angle.gif",
    dual_spool_holder_model,
    [
        {
            "Render_Mode": "model_preview",
            "Image_Render": 1,
            "Tilt_Angle": tilt_angle,
        }
        for tilt_angle in [0, 5, 9.5, 15, 20, 25, 30]
    ],
    camera="0,0,90,90,0,80,900",
)

b.InsetImage(
    "photo-inset.jpg",
    "photo-spools-front-offset.jpg",
    "render-model-preview.png",
    resize="33%",
    gravity="southeast",
)

b.Source(
    "*.scad",
    "sovol-sv06-filament-barrel-rotated.stl",
    "sovol-sv06-JXHSV06-07003-d Barrel nut.STL",
    "sovol-sv06-JXHSV06-02005-d Gantry beam.STL",
    "sovol-sv06-JXHSV06-07002-d Filament Barrel.STL",
)

b.add_default_targets()

# vim: ft=python
